version: '3.9'
services:
  db:
    build: ./Database/
    profiles: ["db", "all"]
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    networks:
      backend:
        ipv4_address: 10.5.0.2
    healthcheck:
      test: pg_isready -h 10.5.0.2 -U postgres
      interval: 10s
      timeout: 5s
      retries: 10
  api:
    build: ./API
    profiles: ["api", "all"]
    ports:
      - 8080:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    depends_on:
      db:
        condition: service_healthy
    networks:
      backend:
        ipv4_address: 10.5.0.3
networks:
  backend:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
         gateway: 10.5.0.1